spring.application.name=adsdentalapp

spring.datasource.url=jdbc:postgresql://localhost:5432/ads_dental
spring.datasource.username=postgres
spring.datasource.password=9328
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

server.error.include-stacktrace=never
server.error.include-exception=false
server.error.include-binding-errors=never
server.error.include-message=always
spring.jackson.serialization.indent_output=true

spring.devtools.restart.enabled=true
spring.devtools.livereload.enabled=true